name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test - Neovim ${{ matrix.nvim-version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.nvim-version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        nvim-version: [
          'v0.11.0',
          'v0.11.1',
          'v0.11.2',
          'v0.11.3',
          'nightly'
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.nvim-version }}

    - name: Verify Neovim installation
      run: nvim --version

    - name: Run tests
      run: make test

  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.11.3

    - name: Cache luarocks
      uses: actions/cache@v4
      with:
        path: ~/.luarocks
        key: luarocks-${{ runner.os }}

    - name: Install luarocks and luacheck
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        # Install system-wide since we're running as root in containers
        sudo luarocks install luacheck
        # Also add luarocks lib path for lua modules
        echo "LUA_PATH=/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;;" >> $GITHUB_ENV

    - name: Cache stylua
      uses: actions/cache@v4
      id: cache-stylua
      with:
        path: ~/.local/bin/stylua
        key: stylua-${{ runner.os }}

    - name: Install stylua
      if: steps.cache-stylua.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.local/bin
        # Download and extract stylua
        curl -L --fail https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip -o stylua.zip
        unzip -o stylua.zip
        mv stylua ~/.local/bin/
        chmod +x ~/.local/bin/stylua
        rm stylua.zip

    - name: Add local bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify installations
      run: |
        nvim --version
        luacheck --version
        stylua --version

    - name: Check formatting
      run: make format-check

    - name: Run lint
      run: make lint

    - name: Check documentation
      run: make doc-check
